#!/usr/bin/python3
a = int(input("input a integer:"))
b = int(input("input another integer:"))
print("a+B=",(a+b))
print("a-b=",(a-b))
print("a*b=",(a*b))
print("a/b=",a/b)
print("a%b=",a%b)
print("+-*/%")
print("zhe hsi yi ge jan dan de cheng cchu fa yun suan ")
